# Generated by Django 4.2.5 on 2023-10-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="prod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("deisc", models.CharField(max_length=200)),
                ("price", models.IntegerField(default=10)),
                (
                    "thumbnail",
                    models.URLField(
                        default="https://cdn.pixabay.com/photo/2016/10/06/19/59/sign-1719892_1280.png"
                    ),
                ),
            ],
        ),
    ]
